version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 cp dist/ s3://lieldevops-vpro-arts/ --recursive

artifacts:
  files: dist/**
  discard-paths: yes
